--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VectorNetworkProject/Vector-Network-Project
branches:
- master
- dev/adjustment
projects:
  Vector-Network-Project:
    path: ""
...
