name: Games_Core
main: Core\Main
api: 3.0.0
version: 0.0.5
commands:
  gamehelp:
    usage: "/gamehelp"
    permission: vector.network.player
    description: "Vector Network で使えるコマンド一覧を表示します。"
permissions:
  vector.network.player:
    default: true
  vector.network.admin:
    default: op